"""Destination unique constraint

Revision ID: 271864dfa580
Revises: d5c86b97d3b1
Create Date: 2026-09-10 14:58:18.341581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271864dfa580'
down_revision: Union[str, Sequence[str], None] = 'd5c86b97d3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_destination_name_location', 'destinations', ['name', 'location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_destination_name_location', 'destinations', type_='unique')
    # ### end Alembic commands ###
